#!/usr/bin/env python3
import json, random, hashlib, math

SEED = 202609250415
rng = random.Random(SEED)


def inv(a,q):
    return pow(a % q, -1, q)

def dot(a,b,q):
    return sum((x*y) for x,y in zip(a,b)) % q

def matmul(A,B,q):
    if not A or not B: return []
    bt=list(zip(*B))
    return [[sum(x*y for x,y in zip(row,col))%q for col in bt] for row in A]

def matvec(A,x,q):
    return [sum(a*b for a,b in zip(row,x))%q for row in A]

def tmatvec(A,x,q):
    return [sum(A[i][j]*x[i] for i in range(len(A)))%q for j in range(len(A[0]))]

def transpose(A): return [list(x) for x in zip(*A)]
def addv(a,b,q): return [(x+y)%q for x,y in zip(a,b)]
def subv(a,b,q): return [(x-y)%q for x,y in zip(a,b)]
def addm(A,B,q): return [[(x+y)%q for x,y in zip(ar,br)] for ar,br in zip(A,B)]
def subm(A,B,q): return [[(x-y)%q for x,y in zip(ar,br)] for ar,br in zip(A,B)]
def scalarmul(a,v,q): return [(a*x)%q for x in v]
def outer(a,b,q): return [[x*y%q for y in b] for x in a]
def hstack(A,B): return [ra+rb for ra,rb in zip(A,B)]
def vstack(A,B): return A+B

def rank(A,q):
    if not A: return 0
    M=[row[:] for row in A]
    m,n=len(M),len(M[0]); r=0
    for c in range(n):
        piv=next((i for i in range(r,m) if M[i][c]%q),None)
        if piv is None: continue
        M[r],M[piv]=M[piv],M[r]
        z=inv(M[r][c],q)
        M[r]=[(z*x)%q for x in M[r]]
        for i in range(m):
            if i!=r and M[i][c]%q:
                z=M[i][c]%q
                M[i]=[(a-z*b)%q for a,b in zip(M[i],M[r])]
        r+=1
        if r==m: break
    return r

def rref_solve(A,b,q):
    M=[row[:] + [bb%q] for row,bb in zip(A,b)]
    m=len(M); n=len(A[0]) if A else 0; r=0; piv=[]
    for c in range(n):
        p=next((i for i in range(r,m) if M[i][c]%q),None)
        if p is None: continue
        M[r],M[p]=M[p],M[r]
        z=inv(M[r][c],q); M[r]=[(z*x)%q for x in M[r]]
        for i in range(m):
            if i!=r and M[i][c]%q:
                z=M[i][c]%q
                M[i]=[(a-z*bb)%q for a,bb in zip(M[i],M[r])]
        piv.append(c); r+=1
    for i in range(r,m):
        if all(M[i][j]%q==0 for j in range(n)) and M[i][-1]%q:
            return None
    x=[0]*n
    for i,c in enumerate(piv): x[c]=M[i][-1]%q
    return x

def centered(a,q):
    a%=q
    return a if a<=q//2 else a-q

def cvec(v,q): return [centered(x,q) for x in v]
def norm2(v,q=None):
    if q is not None: v=cvec(v,q)
    return sum(x*x for x in v)

def mv_int(A,x): return [sum(a*b for a,b in zip(row,x)) for row in A]

def randmat(r,c,q): return [[rng.randrange(q) for _ in range(c)] for _ in range(r)]
def smallmat(r,c,b=1): return [[rng.randint(-b,b) for _ in range(c)] for _ in range(r)]

def make_P_annihilate(y, rows, q):
    # require y[0] nonzero; choose random tail and solve p0
    assert y[0]%q
    P=[]
    for _ in range(rows):
        tail=[rng.randrange(q) for _ in range(len(y)-1)]
        s=sum(t*yy for t,yy in zip(tail,y[1:]))%q
        p0=(-s*inv(y[0],q))%q
        P.append([p0]+tail)
    return P

def compiler_instance(q=65537,n=4,m0=7,ell=6,r=3,y=None):
    if y is None: y=[1,1,0,0,0,0]
    y=[a%q for a in y]
    P=make_P_annihilate(y,r,q)
    h=[1]+[0]*(ell-1)
    # normalize y by h; default y0=1
    assert dot(h,y,q)==1
    u=[rng.randrange(q) for _ in range(n)]
    if not any(u): u[0]=1
    G=randmat(n,r,q)
    T=addm(outer(u,h,q),matmul(G,P,q),q)
    A0=randmat(n,m0,q)
    Ksmall=smallmat(m0,ell,1)
    AK=matmul(A0, [[x%q for x in row] for row in Ksmall], q)
    B=subm(T,AK,q)
    A=hstack(A0,B)
    F=vstack([[x%q for x in row] for row in Ksmall], [[1 if i==j else 0 for j in range(ell)] for i in range(ell)])
    assert matmul(A,F,q)==T
    return A,F,P,h,u,G,T,y,Ksmall

def decryption_trial():
    q=65537
    A,F,P,h,u,G,T,y,K=compiler_instance(q=q)
    z=matvec(F,y,q)
    assert matvec(A,z,q)==u
    tail=z[-len(y):]
    assert tail==y
    # small centered z because y is tiny and K entries tiny
    zc=cvec(z,q)
    s=[rng.randrange(q) for _ in range(len(A))]
    e=[rng.randint(-1,1) for _ in range(len(A[0]))]
    eprime=rng.randint(-1,1)
    c1=[(v+ee)%q for v,ee in zip(tmatvec(A,s,q),e)]
    theta=dot(u,s,q)
    # one encrypted bit, q/4 spacing (not a deployment encoding)
    mu=rng.randrange(2); Delta=q//4
    c2=(theta+eprime+mu*Delta)%q
    raw=(c2-dot(z,c1,q))%q
    residual=centered(raw-mu*Delta,q)
    expected=eprime-sum(zz*ee for zz,ee in zip(zc,e))
    assert residual==expected
    # exact public projection identity F^T c1 = h*theta + P^T G^T s + F^T e
    lhs=tmatvec(F,c1,q)
    Gts=tmatvec(G,s,q)
    rhs=addv(scalarmul(theta,h,q),tmatvec(P,Gts,q),q)
    rhs=addv(rhs,tmatvec(F,[ee%q for ee in e],q),q)
    assert lhs==rhs
    return max(abs(x) for x in zc), abs(residual), norm2(zc)

def dense_false_instance(q=101,ell=5):
    # unique normalized kernel generated by a deliberately dense vector.
    y=[20,19,18,17,16][:ell]
    P=make_P_annihilate(y,ell-1,q)
    # regenerate until rank ell-1
    while rank(P,q)<ell-1:
        P=make_P_annihilate(y,ell-1,q)
    h=[inv(y[0],q)]+[0]*(ell-1)
    assert dot(h,y,q)==1 and matvec(P,y,q)==[0]*(ell-1)
    sol=rref_solve(P+[h],[0]*(ell-1)+[1],q)
    assert sol is not None
    # uniqueness follows rank([P;h])=ell
    assert rank(P+[h],q)==ell
    assert sol==[v%q for v in y]
    beta2=200
    assert norm2(sol,q)>beta2
    n=4; G=randmat(n,ell-1,q); u=[rng.randrange(q) for _ in range(n)]
    if not any(u):u[0]=1
    T=addm(outer(u,h,q),matmul(G,P,q),q)
    assert matvec(T,sol,q)==u
    M=transpose(T) # rows are target directions m_j^T
    # y^T M = u^T
    yTM=[sum(sol[j]*M[j][i] for j in range(ell))%q for i in range(n)]
    assert yTM==u
    assert rank(M+[u],q)==rank(M,q)  # WWW full-rank gate fails
    return norm2(sol,q), rank(M,q), rank(M+[u],q)

def anchor_rowspace_equiv_trial(q=101,ell=7,r=4):
    P=randmat(r,ell,q)
    # force full row rank for clean equivalence controls
    while rank(P,q)<r: P=randmat(r,ell,q)
    if rng.randrange(2):
        coeff=[rng.randrange(q) for _ in range(r)]
        h=[sum(coeff[i]*P[i][j] for i in range(r))%q for j in range(ell)]
        inrow=True
    else:
        h=[rng.randrange(q) for _ in range(ell)]
        while rank(P+[h],q)==rank(P,q): h=[rng.randrange(q) for _ in range(ell)]
        inrow=False
    sol=rref_solve(P+[h],[0]*r+[1],q)
    assert (sol is None)==inrow
    if sol is not None:
        assert matvec(P,sol,q)==[0]*r and dot(h,sol,q)==1
    return inrow

def main():
    out={
        'run':95,
        'seed':SEED,
        'scope':'finite-field algebra / toy dual-Regev correctness and WWW transversality controls only; no LWE/SIS/QPT security experiment',
    }
    dec=[]
    for _ in range(500): dec.append(decryption_trial())
    out['affine_common_target_trials']={
        'count':len(dec),
        'max_abs_decoder_coordinate':max(x[0] for x in dec),
        'max_abs_decryption_residual':max(x[1] for x in dec),
        'max_decoder_norm2':max(x[2] for x in dec),
        'identities':['A F = u h^T + G P','P y = 0','h^T y = 1','A(Fy)=u','tail(Fy)=y','dual-Regev residual','F^T c projection']
    }
    dense=[]
    for _ in range(500): dense.append(dense_false_instance())
    out['dense_false_gap_transversality_trials']={
        'count':len(dense),
        'min_unique_normalized_norm2':min(x[0] for x in dense),
        'short_norm2_cutoff':200,
        'all_no_short_normalized_relation':all(x[0]>200 for x in dense),
        'all_www_rank_gate_failed':all(a==b for _,a,b in dense),
    }
    eq=[anchor_rowspace_equiv_trial() for _ in range(1000)]
    out['anchor_rowspace_equivalence_trials']={
        'count':len(eq),'h_in_rowspace_cases':sum(eq),'h_outside_rowspace_cases':len(eq)-sum(eq),
        'checked_equivalence':'exists y: P y=0 and h^T y=1  iff  h notin rowspan(P)'
    }
    # symbolic parameter table for correctness/source-gap tension.
    table=[]
    for d,gamma,ell in [(16,8,4096),(32,16,16384),(64,32,65536),(128,64,262144)]:
        honest=math.sqrt(d); dense=math.sqrt(ell); false=math.sqrt(gamma*d)
        table.append({'d':d,'gamma':gamma,'ell':ell,'honest_l2_B1':honest,'false_min_l2_B1':false,'dense_public_reference_l2_upper':dense,'gap_sqrt_gamma':math.sqrt(gamma)})
    out['bounded_alphabet_gap_table']=table
    out['status']='PASS'
    raw=json.dumps(out,sort_keys=True,indent=2)+'\n'
    print(raw,end='')

if __name__=='__main__': main()
